-- Phase 3: Pedagogy Analysis Schema
-- Add pedagogy_analysis column to lessons table

-- Add new column for pedagogy analysis
ALTER TABLE public.lessons 
ADD COLUMN IF NOT EXISTS pedagogy_analysis JSONB;

-- Add comment explaining the column
COMMENT ON COLUMN public.lessons.pedagogy_analysis IS 
'Pedagogical analysis including question types, teaching strategies, and identified pedagogies. Generated by Phase 3 analysis pipeline.';

-- Create index for better query performance on JSONB column
CREATE INDEX IF NOT EXISTS idx_lessons_pedagogy_analysis 
ON public.lessons USING gin (pedagogy_analysis);

-- Verify the column was added
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'lessons' 
        AND column_name = 'pedagogy_analysis'
    ) THEN
        RAISE NOTICE 'Column pedagogy_analysis successfully added to lessons table';
    ELSE
        RAISE EXCEPTION 'Failed to add pedagogy_analysis column';
    END IF;
END $$;

